packages:
    - 'packages/*'
    - 'tools/*'
    - 'site'

overrides:
  rolldown: latest

catalog:
    vite: ^8.0.1
    typescript: npm:@typescript/native-preview@latest

catalogs:
    typescript-stable:
        typescript: ^6.0.2