packages:
  - 'packages/*'
  - 'tools/*'
  - 'site'

catalog:
  typescript: npm:@typescript/native-preview@latest
  vite: ^8.0.3

catalogs:
  typescript-stable:
    typescript: ^6.0.2

overrides:
  rolldown: latest
