packages:
  - 'packages/*'
  - 'tools/*'
  - 'site'

catalog:
  typescript: npm:@typescript/native-preview@latest
  vite: ^8.0.11

catalogs:
  typescript-stable:
    typescript: ^6.0.3

overrides:
  rolldown: ^1.0.0

sharedWorkspaceLockfile: false
ignoreWorkspaceCycles: true