export default [
    'Accents',
    'Actions',
    'Activities',
    'Arrows',
    'Business',
    'Communication & Cloud',
    'Design',
    'Development',
    'Emojis',
    'Files',
    'Food & Drink',
    'Gestures',
    'Layout',
    'Logos & Brands',
    'Math & Numbers',
    'Media',
    'Miscellaneous',
    'Nature',
    'Objects',
    'Organization',
    'Places & Transportation',
    'Security',
    'Shapes',
    'Status',
    'System & Interface',
    'Technology',
    'Text',
    'Weather',
    'Window',
]
