export default [
    'Accessibility',
    'Add',
    'Add Circle',
    'Add Rhombus',
    'Add Square',
    'Add Square Multiple',
    'Airplane',
    'Airplane Landing',
    'Airplane Takeoff',
    'Alert Circle',
    'Alert Triangle',
    'Align Bottom',
    'Align Horizontal Centers',
    'Align Left',
    'Align Right',
    'Align Top',
    'Align Vertical Centers',
    'Amazon',
    'Anchor',
    'Android',
    'Angle',
    'App Remove',
    'App Store',
    'Apple',
    'Apps',
    'Apps Add',
    'Apps List',
    'Arc',
    'Archive',
    'Archive Add 2',
    'Arrow Clockwise',
    'Arrow Counterclockwise',
    'Arrow Down',
    'Arrow Download',
    'Arrow Enter',
    'Arrow Export',
    'Arrow Forward',
    'Arrow Import',
    'Arrow Left',
    'Arrow Left Right',
    'Arrow Maximize',
    'Arrow Minimize',
    'Arrow Move',
    'Arrow Redo',
    'Arrow Redo 2',
    'Arrow Reply',
    'Arrow Right',
    'Arrow Rotate Clockwise',
    'Arrow Rotate Counterclockwise',
    'Arrow Sort',
    'Arrow Swap',
    'Arrow Sync',
    'Arrow Sync 2',
    'Arrow Trending',
    'Arrow Undo',
    'Arrow Undo 2',
    'Arrow Up',
    'Arrow Up Down',
    'Arrow Upload',
    'Attach',
    'Background Color',
    'Background Color Accent',
    'Backspace',
    'Badge',
    'Bank',
    'Bar Graph',
    'Battery',
    'Battery Full',
    'Beach',
    'Beaker',
    'Bell',
    'Bell Dot',
    'Bell Off',
    'Bluesky',
    'Bluetooth',
    'Board',
    'Bolt',
    'Book',
    'Book 2',
    'Book Add',
    'Book Add 2',
    'Book Info',
    'Book Info 2',
    'Book Open',
    'Bookmark',
    'Bookmark Add',
    'Bookmark Multiple',
    'Border All',
    'Box',
    'Box Drag',
    'Box Margins',
    'Braces',
    'Braces Variable',
    'Brackets',
    'Branch',
    'Branch Compare',
    'Branch Fork',
    'Branch Fork 2',
    'Branch Pull Request',
    'Briefcase',
    'Briefcase 2',
    'Brightness',
    'Broom',
    'Bug',
    'Building Multiple',
    'Button',
    'CSS',
    'CSS 2',
    'Cake',
    'Calculator',
    'Calendar',
    'Calligraphy Pen',
    'Camera',
    'Cancel',
    'Cancel Circle',
    'Cancel Octagon',
    'Cancel Square',
    'Candy',
    'Cart',
    'Cent',
    'Center Horizontal',
    'Center Vertical',
    'Chat',
    'Checkbox Checked',
    'Checkbox Indeterminate',
    'Checkbox Indeterminate 2',
    'Checkbox Unchecked',
    'Checkmark',
    'Checkmark Circle',
    'Checkmark Starburst',
    'Chevron Down',
    'Chevron Left',
    'Chevron Right',
    'Chevron Up',
    'Chrome Restore',
    'Circle',
    'Circle Small',
    'Clipboard',
    'Clipboard Paste',
    'Clipboard Search',
    'Clock',
    'Closed Captions',
    'Cloud',
    'Code',
    'Coffee Hot',
    'Color Palette',
    'Comment',
    'Comment Add',
    'Comment Add 2',
    'Comment Exclamation',
    'Comment Multiple',
    'Compare Size',
    'Compass',
    'Component',
    'Compose',
    'Computer',
    'Computer Mac',
    'Contract Down',
    'Cookies',
    'Copy',
    'Copyleft',
    'Copyright',
    'Corner Radius',
    'Credit Card',
    'Crop',
    'Cursor',
    'Cursor Click',
    'Cursor Drag',
    'Cut',
    'Dark Theme',
    'Database',
    'Database Add',
    'Delete',
    'Diamond',
    'Directions',
    'Do Not Disturb',
    'Document',
    'Dollar',
    'Dollar Circle',
    'Door',
    'Door Open',
    'Draw Text',
    'Drop',
    'Emoji',
    'Emoji Frown',
    'Emoji Grin',
    'Emoji Laughter',
    'Eraser',
    'Expand',
    'Extension',
    'Eye',
    'Eye Off',
    'Eyedropper',
    'Eyedropper Color',
    'Eyedropper Color Accent',
    'Facebook',
    'Fast Forward',
    'Figma',
    'File',
    'File Add',
    'File Multiple',
    'File Sync',
    'Filter',
    'Filter 2',
    'Filter Cancel',
    'Filter Cancel 2',
    'Flag',
    'Flag 2',
    'Flashlight',
    'Foldable Horizontal',
    'Foldable Horizontal Half',
    'Foldable Vertical',
    'Foldable Vertical Half',
    'Folder',
    'Folder Add',
    'Folder Multiple',
    'Folder Open',
    'Full Screen Maximize',
    'Full Screen Minimize',
    'Game',
    'Gift',
    'Git Commit',
    'GitHub',
    'GitLab',
    'Globe',
    'Google',
    'Google 2',
    'Google Chrome',
    'Google Play',
    'Graph',
    'Grid',
    'Grid Dots',
    'HTML',
    'Hamburger',
    'Hand',
    'Hard Drive',
    'Hash',
    'Hat Graduation',
    'Headphones',
    'Headphones Off',
    'Heart',
    'Heart Stylistic',
    'Hexagon',
    'Highlighter',
    'Highlighter Accent',
    'History',
    'Home',
    'Home 2',
    'Hourglass',
    'Infinity',
    'Info',
    'Instagram',
    'JavaScript',
    'Keyboard',
    'Keyboard Command',
    'Keyboard Shift',
    'Laptop',
    'Layers',
    'Layout',
    'Leaf',
    'Leaf Three',
    'Leaf Two',
    'Library',
    'Lightbulb',
    'Line Diagonal',
    'Link',
    'Linux',
    'Location',
    'Lock',
    'Lock Open',
    'Mail',
    'Mail Open',
    'Map',
    'Mask',
    'Math',
    'Megaphone',
    'Megaphone Loud',
    'Mention',
    'Menu',
    'Microphone',
    'Microphone Off',
    'Microsoft',
    'Microsoft Edge',
    'Moon',
    'More',
    'More Vertical',
    'Motherboard',
    'Movie',
    'Music Note',
    'Music Note 2',
    'NPM',
    'Narrator',
    'NodeJS',
    'Note',
    'Note Add',
    'Octagon',
    'Open',
    'Open Source',
    'PDF',
    'PDF 2',
    'Page Margins',
    'Paint Bucket',
    'Paint Bucket Accent',
    'Paintbrush',
    'Paintbrush 2',
    'Panel Bottom',
    'Panel Bottom Open',
    'Panel Left',
    'Panel Left Contract',
    'Panel Left Expand',
    'Panel Left Open',
    'Panel Right',
    'Panel Right Contract',
    'Panel Right Expand',
    'Panel Right Open',
    'Parentheses',
    'Pause',
    'Pencil',
    'Pentagon',
    'Person',
    'Person 2',
    'Person Add',
    'Person Add 2',
    'Person Circle',
    'Person Multiple',
    'Phone',
    'Phone Accept',
    'Phone Hang Up',
    'Photo',
    'Photo Filter',
    'Photo Multiple',
    'Picture in Picture',
    'Picture in Picture 2',
    'Picture in Picture Enter',
    'Picture in Picture Exit',
    'Pin',
    'Pin Off',
    'Play',
    'Play Circle',
    'Printer',
    'Prohibited',
    'Python',
    'QR Code',
    'Question',
    'Question Circle',
    'Quote',
    'ReactJS',
    'Record',
    'Record Stop',
    'Rectangle Wide',
    'Regular Expression',
    'Reverse',
    'Rhombus',
    'Ribbon',
    'Ribbon Star',
    'Roblox',
    'Ruler',
    'Ruler Diagonal',
    'Save',
    'Save Multiple',
    'Save Pencil',
    'Screen Size',
    'Script',
    'Script 2',
    'Search',
    'Search Cancel',
    'Section Break',
    'Send',
    'Server',
    'Settings',
    'Shape Difference',
    'Shape Intersect',
    'Shape Subtract',
    'Shape Union',
    'Shield',
    'Shield Cancel',
    'Shield Checkmark',
    'Shield Keyhole',
    'Skull',
    'Slash Square',
    'Soundwave',
    'Spacebar',
    'Sparkle',
    'Spinner',
    'Split Horizontal',
    'Split Vertical',
    'Square',
    'Star',
    'Stroke Thickness',
    'Subtract',
    'Svelte',
    'Symbols',
    'TV',
    'Table',
    'Table Simple',
    'Tablet',
    'Tag',
    'Tag Accent',
    'Tag Multiple',
    'Task List',
    'Terminal',
    'Text',
    'Text Add',
    'Text Align Center',
    'Text Align Justify',
    'Text Align Left',
    'Text Align Right',
    'Text Bold',
    'Text Bullet List',
    'Text Bullet List Square',
    'Text Bullet List Square Add',
    'Text Case Lowercase',
    'Text Case Title',
    'Text Case Uppercase',
    'Text Clear Formatting',
    'Text Collapse',
    'Text Color',
    'Text Color Accent',
    'Text Edit Style',
    'Text Effects',
    'Text Expand',
    'Text Font',
    'Text Font Size',
    'Text Footnote',
    'Text Highlight Color',
    'Text Highlight Color Accent',
    'Text Indent Decrease',
    'Text Indent Increase',
    'Text Italic',
    'Text Large',
    'Text Letter Spacing',
    'Text Line Height',
    'Text Line Spacing',
    'Text Number List',
    'Text Position Bottom',
    'Text Position Middle',
    'Text Position Top',
    'Text Small',
    'Text Strikethrough',
    'Text Subscript',
    'Text Superscript',
    'Text Typography',
    'Text Underline',
    'Thumbs Down',
    'Thumbs Up',
    'TikTok',
    'Timer',
    'Toolbox',
    'Triangle',
    'Tune',
    'TypeScript',
    'Ubuntu',
    'Vehicle Car',
    'Video',
    'Video Clip',
    'Visual Studio Code',
    'Volume',
    'Volume Low',
    'Volume Medium',
    'Volume Mute',
    'VueJS',
    'Watch',
    'Weather Cloudy',
    'Webpack',
    'Wi-Fi',
    'Window',
    'Window Add',
    'Window Multiple',
    'Wrench',
    'X (Twitter)',
    'YouTube',
    'YouTube Shorts',
    'Zoom In',
    'Zoom Out',
]
