export default [
    'Add',
    'Add Circular',
    'Search Cancel',
    'Add Rhombus',
    'Add Square',
    'Add Square Multiple',
    'Add Square Multiple -Var',
    'App Remove',
    'Apps',
    'Apps Add',
    'Backspace',
    'Cancel',
    'Checkmark',
    'Compose',
    'Copy',
    'Copy -Var',
    'Crop',
    'Cut',
    'Delete',
    'Eye',
    'Eye Off',
    'Fast Foward',
    'Heart',
    'Heart Stylistic',
    'Keyboard Shift',
    'More',
    'More Vertical',
    'Pause',
    'Pencil',
    'Play',
    'Play Circular',
    'Reverse',
    'Search',
    'Star',
    'Tune',
    'Checkmark Starburst',
    'Credit Card',
    'Lock',
    'Lock Open',
    'Shield',
    'Shield Cancel',
    'Shield Checkmark',
    'Shield Keyhole',
    'Chat',
    'Cloud',
    'Comment',
    'Comment Multiple',
    'Comment Multiple -Var',
    'Database',
    'Database Add',
    'Globe',
    'Mail',
    'Mail Open',
    'Megaphone',
    'Megaphone Loud',
    'Mention',
    'Narrator',
    'Person',
    'Person 2',
    'Person Add',
    'Person Add 2',
    'Person Circle',
    'Person Multiple',
    'Phone Accept',
    'Phone Hang Up',
    'Send',
    'Wi-Fi',
    'Anchor',
    'Attatch',
    'Book Info 2',
    'Calendar',
    'Diamond',
    'Eraser',
    'Eyedropper',
    'Eyedropper Color',
    'Flashlight',
    'Gift',
    'Hat Graduation',
    'Highlighter',
    'Hourglass',
    'Layers',
    'Lightbulb',
    'Link',
    'Microphone',
    'Microphone Off',
    'Pin',
    'Pin Off',
    'Timer',
    'Wrench',
    'Alert Circle',
    'Alert Triangle',
    'Arrow Sync',
    'Arrow Sync 2',
    'Badge',
    'Bell',
    'Cancel Circle',
    'Cancel Square',
    'Checkmark Circle',
    'Clock',
    'Do Not Disturb',
    'Info',
    'Prohibited',
    'Spinner',
    'Emoji',
    'Emoji Frown',
    'Emoji Grin',
    'Emoji Laughter',
    'Skull',
    'Arrow Clockwise',
    'Arrow Counterclockwise',
    'Arrow Down',
    'Arrow Download',
    'Arrow Enter',
    'Arrow Export',
    'Arrow Foward',
    'Arrow Import',
    'Arrow Left',
    'Arrow Move',
    'Arrow Redo',
    'Arrow Redo 2',
    'Arrow Reply',
    'Arrow Right',
    'Arrow Rotate Clockwise',
    'Arrow Rotate Counterclockwise',
    'Arrow Sort',
    'Arrow Swap',
    'Arrow Trending',
    'Arrow Undo',
    'Arrow Undo 2',
    'Arrow Up',
    'Arrow Up Down',
    'Arrow Left Right',
    'Arrow Upload',
    'Chevron Down',
    'Chevron Left',
    'Chevron Right',
    'Chevron Up',
    'Subtract',
    'Document',
    'Draw Text',
    'Note',
    'Note Add',
    'Quote',
    'Spacebar',
    'Symbols',
    'Text',
    'Text Add',
    'Text Align Center',
    'Text Align Justify',
    'Text Align Left',
    'Text Align Right',
    'Text Bold',
    'Text Case Lowercase',
    'Text Case Title',
    'Text Case Uppercase',
    'Text Clear Formatting',
    'Text Collapse',
    'Text Color',
    'Text Edit Style',
    'Text Effects',
    'Text Expand',
    'Text Font',
    'Text Font Size',
    'Text Footnote',
    'Text Highlight Color',
    'Text Indent Decrease',
    'Text Indent Increase',
    'Text Italic',
    'Text Large',
    'Text Letter Spacing',
    'Text Line Height',
    'Text Line Spacing',
    'Text Number List',
    'Text Position Bottom',
    'Text Position Middle',
    'Text Position Top',
    'Text Small',
    'Text Strikethrough',
    'Text Subscript',
    'Text Superscript',
    'Text Typography',
    'Text Underline',
    'File',
    'File Add',
    'File Sync',
    'Folder',
    'Folder Add',
    'Folder Open',
    'Hard Drive',
    'PDF',
    'PDF 2',
    'Photo',
    'QR Code',
    'Save',
    'Save As',
    'Accessibility',
    'Battery',
    'Battery Full',
    'Button',
    'Checkbox Intermediate 2',
    'Checkbox Unchecked',
    'Checkmark Checked',
    'Checkmark Intermediate',
    'Closed Captions',
    'Cursor',
    'Cursor Click',
    'Dark Theme',
    'Extension',
    'Menu',
    'Settings',
    'Zoom In',
    'Zoom Out',
    'Airplane',
    'Airplane Landing',
    'Airplane Takeoff',
    'Beach',
    'Building Multiple',
    'Component',
    'Directions',
    'Home',
    'Home 2',
    'Location',
    'Map',
    'Museum',
    'Vehicle Car',
    'Bar Graph',
    'Box Margins',
    'Clipboard',
    'Clipboard Paste',
    'Clipboard Search',
    'Compare Size',
    'Grid',
    'Grid Dots',
    'Layout',
    'Page Margins',
    'Panel Left',
    'Panel Left Contract',
    'Panel Left Expand',
    'Panel Left Open',
    'Panel Right Open',
    'Panel Right',
    'Panel Right Contract',
    'Panel Right Expand',
    'Table',
    'Table Simple',
    'Background Color',
    'Border All',
    'Color Palette',
    'Mask',
    'Paint Bucket',
    'Paintbrush',
    'Paintbrush 2',
    'Shape Difference',
    'Shape Intersect',
    'Shape Subtract',
    'Shape Union',
    'Stroke Thickness',
    'Arrow Maximize',
    'Arrow Minimize',
    'Chrome Restore',
    'Chrome Restore -Var',
    'Contract Down',
    'Expand',
    'Full Screen Maximize',
    'Full Screen Minimize',
    'Open',
    'Picture in Picture',
    'Picture in Picture 2',
    'Picture in Picture Enter',
    'Picture in Picture Exit',
    'Window',
    'Window Multiple',
    'Window Multiple -Var',
    'Beaker',
    'Braces',
    'Braces Variable',
    'Branch',
    'Branch Compare',
    'Branch Fork',
    'Branch Fork 2',
    'Bug',
    'Code',
    'Git Commit',
    'Script',
    'Script 2',
    'Terminal',
    'Video Clip',
    'Arc',
    'Circle',
    'Circle Small',
    'Corner Radius',
    'Hexagon',
    'Line Diagonal',
    'Octagon',
    'Pentagon',
    'Rectangle Wide',
    'Rhombus',
    'Square',
    'Triangle',
    'Background Color Accent',
    'Eyedropper Color Accent',
    'Highlighter Accent',
    'Paint Bucket Accent',
    'Tag Accent',
    'Text Color Accent',
    'Text Highlight Color Accent',
    'Amazon',
    'App Store',
    'Apple',
    'Bluetooth',
    'CSS',
    'Facebook',
    'Figma',
    'GitHub',
    'Google',
    'Google 2',
    'Google Chrome',
    'Google Play',
    'HTML',
    'Instagram',
    'JavaScript',
    'Microsoft',
    'Microsoft Edge',
    'Python',
    'Roblox',
    'TikTok',
    'Visual Studio Code',
    'X (Twitter)',
    'YouTube',
    'YouTube Shorts',
    'Book',
    'Book 2',
    'Book Add',
    'Book Add 2',
    'Book Info',
    'Book Open',
    'Box',
    'Broom',
    'Calligraphy Pen',
    'Cart',
    'Compass',
    'Flag',
    'Library',
    'Photo Filter',
    'Ribbon',
    'Ribbon Star',
    'Video',
    'Briefcase',
    'Briefcase 2',
    'Cent',
    'Dollar',
    'Graph',
    'Toolbox',
    'Cake',
    'Coffee Hot',
    'Cookies',
    'Drop',
    'Hamburger',
    'Box Drag',
    'Cursor Drag',
    'Hand',
    'Thumbs Down',
    'Thumbs Up',
    'Angle',
    'Calculator',
    'Hash',
    'Ruler',
    'Screen Size',
    'Headphones',
    'Movie',
    'Music Note',
    'Music Note 2',
    'Soundwave',
    'Volume',
    'Volume 0',
    'Volume 1',
    'Volume Mute',
    'Leaf',
    'Leaf Three',
    'Leaf Two',
    'History',
    'Question',
    'Question Circle',
    'Sparkle',
    'Align Bottom',
    'Align Horizontal Centers',
    'Align Left',
    'Align Right',
    'Align Top',
    'Align Vertical Centers',
    'Apps List',
    'Archive',
    'Archive Add 2',
    'Board',
    'Bookmark',
    'Bookmark Add',
    'Bookmark Multiple',
    'Bookmark Multiple -Var',
    'Center Horizontal',
    'Center Vertical',
    'Filter',
    'Filter 2',
    'Filter Cancel',
    'Filter Cancel 2',
    'Section Break',
    'Tag',
    'Tag Multiple',
    'Tag Multiple -Var',
    'Task List',
    'Text Bullet List',
    'Text Bullet List Square',
    'Text Bullet List Square Add',
    'Camera',
    'Computer',
    'Computer Mac',
    'Foldable Horizontal',
    'Foldable Horizontal Half',
    'Foldable Vertical',
    'Foldable Vertical Half',
    'Game',
    'Keyboard',
    'Laptop',
    'Motherboard',
    'Phone',
    'Printer',
    'TV',
    'Tablet',
    'Watch',
    'Brightness',
    'Moon',
    'Weather Cloudy',
    'Branch ',
    'Ubuntu',
    'Linux',
    'Webpack',
    'NPM',
    'NodeJS',
    'Bolt',
    'Door',
    'Open Source',
    'VueJS',
    'Record',
    'Record Stop',
    'Door Open',
    'Branch Pull Request',
    'Candy',
    'Svelte',
];
